### ISSUE TITLE
Passing the <embedding_function> to <LanceDBDocumentStore>

### ISSUE THREAD

**Issue by farzbood** [alanmeeson/lancedb-haystack#1]
Hi,
As of my experience, seems there's no way to tell the **LanceDB** to use **Embedding-Function** (e.g: Sentence Transformer) other than it's default (which is one by openai) through `lancedb-haystack` -> `LanceDBDocumentStore`!
**LanceDB** itself supports that internally, BTW.
(https://lancedb.github.io/lancedb/embeddings/#sentence-transformers-embedding-function)

Is there an intuitive workflow to achieve that?
PEACE V

**Comment by alanmeeson** [comment]
Alas no, and there isn't one on the roadmap either.

By design, the `LanceDBDocumentStore` doesn't do any of the embedding itself, but rather leaves that to `TextEmbedder`and `DocumentEmbedder` components elsewhere in the haystack pipeline. Take a look in the example notebook to see what I mean.
